#image: gutenye/debian-devel-with-guten
image: fooc
script:
  #- '[[ $(git show-ref $(git describe --abbrev=0 --tags)) == $(git rev-parse HEAD) ]] || exit 2'
cache:
  - /root/.aptly

deploy:
  bash:
    script:
      - cd misc/deb && gutdeb publish $(cat ../../VERSION)
